#!/usr/bin/env bash

case $1 in
 "up")
  docker-compose  -f buildSrc/docker/docker-compose.yml  $1 --detach $2 $3 $3 $5
  ;;
  "clean")
   docker volume rm docker_snapcoach_pgadmin
   docker volume rm docker_snapcoach_postgres
  ;;
  *)
  docker-compose  -f buildSrc/docker/docker-compose.yml  $1 $2 $3 $3 $5
  ;;
esac

